name: Rust Test

on:
  push:
    branches: ["main"]
    tags-ignore:
      - "v*.*.*"
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: {{crate_name | kebab_case}}-${{ "runner.os" | prepend: "{{ " | append: " }}" }}-cargo
          key: {{crate_name | kebab_case}}-${{ "runner.os" | prepend: "{{ " | append: " }}" }}-cargo
      - uses: davidB/rust-cargo-make@v1
      - name: Run linter
        run: cargo clippy -- --deny warnings
      - name: Run tests
        run: cargo test
